import React from 'react'
import Pixel from './Pixel'

const App = () => {
  return (
    <div id="app">
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/> 
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>
      <Pixel/>

    </div>
  )
}

export default App
